Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -113,16 +113,16 @@ jobs:
           create_new_workflow_run() {
             local workflow_id="CI.yml"
             local ref="arenapvp"
-            
-            curl -L \
-              -X POST \
-              -H "Accept: application/vnd.github+json" \
-              -H "Authorization: Bearer $FINE_GRAINED_PAT" \
-              -H "X-GitHub-Api-Version: 2022-11-28" \
-              "https://api.github.com/repos/$REPO/actions/workflows/$workflow_id/dispatches" \
-              -d "{\"ref\":\"$ref\"}"
           
-            echo "New workflow run created"
+            echo "Creating workflow run for workflow: $workflow_id, ref: $ref"
+          
+            gh workflow run "$workflow_id" --ref "$ref"
+          
+            if [ $? -eq 0 ]; then
+              echo "New workflow run created successfully"
+            else
+              echo "Error creating workflow run. Please check the workflow ID and branch name."
+            fi
           }
 
           cancel_old_workflow_runs() {
